# Generated by Django 6.0 on 2026-01-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
